// Patterns for common secret formats — conservative to minimize false positives
const SECRET_PATTERNS: RegExp[] = [
  /AKIA[0-9A-Z]{16}/g,
  /gh[pousr]_[A-Za-z0-9_]{36,}/g,
  /npm_[A-Za-z0-9]{36,}/g,
  /-----BEGIN (?:RSA |EC |DSA )?PRIVATE KEY-----[\s\S]*?-----END (?:RSA |EC |DSA )?PRIVATE KEY-----/g,
  /(api[_-]?key|apikey|secret|token|password|passwd|auth)\s*[:=]\s*['"]?[^\s'"]{8,}/gi,
  /^([A-Z_]*(SECRET|KEY|TOKEN|PASSWORD|AUTH)[A-Z_]*)=.+$/gm,
];

const GITHUB_MAX_LEN = 65_536;
const TRUNCATE_AT = 60_000;
const DISCLAIMER = '> **Note**: This comment was generated by an AI assistant (claude-swarm). Review carefully before acting on it.\n\n';

/**
 * Redact known secret patterns from text.
 */
export function stripSecrets(text: string): string {
  let result = text;
  for (const pattern of SECRET_PATTERNS) {
    result = result.replace(pattern, (match, group1) => {
      // For named-group patterns (key=value), keep the key name, redact value
      if (group1) {
        const eqIndex = match.indexOf('=');
        const colonIndex = match.indexOf(':');
        const sep = eqIndex !== -1 ? '=' : ':';
        const sepIdx = eqIndex !== -1 ? eqIndex : colonIndex;
        if (sepIdx !== -1) return match.slice(0, sepIdx + 1) + '[REDACTED]';
      }
      return '[REDACTED]';
    });
  }
  return result;
}

/**
 * Truncate text to fit GitHub's comment limit.
 */
export function truncateForGithub(text: string, maxLen = TRUNCATE_AT): string {
  if (text.length <= maxLen) return text;
  const lastNewline = text.lastIndexOf('\n', maxLen);
  const cutAt = lastNewline > 0 ? lastNewline : maxLen;
  return text.slice(0, cutAt) + '\n\n---\n*[Output truncated — exceeded GitHub comment limit]*';
}

/**
 * Prepend AI-generated disclaimer to comment body.
 */
export function addDisclaimer(text: string): string {
  return DISCLAIMER + text;
}

/**
 * Full sanitization pipeline: strip secrets → truncate → add disclaimer.
 */
export function sanitizeComment(text: string): string {
  return addDisclaimer(truncateForGithub(stripSecrets(text)));
}

export { GITHUB_MAX_LEN };
