import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

// Disclaimer prefix defined in comment-sanitizer — duplicated here to avoid circular import
const BOT_DISCLAIMER_PREFIX = '> **Note**: This comment was generated by an AI assistant (claude-swarm).';

export interface IssueComment {
  author: string;
  body: string;
  createdAt: string;
}

// Cache maintainer permission lookups for the session (author → isMaintainer)
const maintainerCache = new Map<string, boolean>();

/**
 * Fetch the last N comments on an issue via gh CLI.
 */
export async function getLastComments(
  repo: string,
  issueNum: number,
  count = 5,
): Promise<IssueComment[]> {
  try {
    const { stdout } = await execFileAsync('gh', [
      'api', `repos/${repo}/issues/${issueNum}/comments`,
      '--jq', `.[-${count}:] | map({ author: .user.login, body: .body, createdAt: .created_at })`,
    ]);
    return JSON.parse(stdout) as IssueComment[];
  } catch {
    return [];
  }
}

/**
 * Detect if a comment was posted by this bot (identified by disclaimer prefix).
 */
export function isBotComment(comment: IssueComment): boolean {
  return comment.body.startsWith(BOT_DISCLAIMER_PREFIX);
}

/**
 * Check if a GitHub user has admin or maintain permission on the repo.
 * Cached per session to avoid repeated API calls.
 */
export async function isMaintainerComment(repo: string, author: string): Promise<boolean> {
  if (maintainerCache.has(author)) return maintainerCache.get(author)!;
  try {
    const { stdout } = await execFileAsync('gh', [
      'api', `repos/${repo}/collaborators/${author}/permission`,
      '--jq', '.permission',
    ]);
    const permission = stdout.trim();
    const result = permission === 'admin' || permission === 'maintain';
    maintainerCache.set(author, result);
    return result;
  } catch {
    maintainerCache.set(author, false);
    return false;
  }
}

/**
 * Decide whether to skip posting a comment.
 *
 * Skip if:
 * - Last comment is from the bot (loop prevention)
 * - Last comment is from a maintainer AND second-to-last is from the bot
 *   (maintainer-last pattern signals discussion is closed)
 */
export async function shouldSkipComment(
  repo: string,
  issueNum: number,
): Promise<{ skip: boolean; reason: string }> {
  const comments = await getLastComments(repo, issueNum);

  if (comments.length === 0) return { skip: false, reason: '' };

  const last = comments[comments.length - 1];
  const secondToLast = comments.length >= 2 ? comments[comments.length - 2] : undefined;

  if (isBotComment(last)) {
    return { skip: true, reason: 'loop-prevention: last comment is bot' };
  }

  const lastIsMaintainer = await isMaintainerComment(repo, last.author);
  if (lastIsMaintainer && secondToLast && isBotComment(secondToLast)) {
    return { skip: true, reason: 'maintainer-last: discussion appears closed' };
  }

  return { skip: false, reason: '' };
}
