import { Command } from 'commander';
import { readFileSync } from 'node:fs';
import { Octokit } from '@octokit/rest';
import { invokeClaudePhase } from '../commands/watch/phases/claude-invoker.js';
import type { ClaudeModel } from '../commands/watch/types.js';

interface BrainstormOptions {
  context?: string;
  repo?: string;
  label?: string;
  model?: string;
}

async function executeBrainstorm(topic: string, options: BrainstormOptions): Promise<void> {
  const modelOverride = options.model as ClaudeModel | undefined;

  let contextContent = '';
  if (options.context) {
    try {
      contextContent = `\n\nAdditional context from ${options.context}:\n${readFileSync(options.context, 'utf8')}`;
    } catch {
      console.error(`Warning: Could not read context file: ${options.context}`);
    }
  }

  const prompt = `Use the /brainstorm skill to analyze this topic with trade-off analysis and brutal honesty.

Topic: ${topic}${contextContent}

Structure your response as:
## Problem
Brief problem statement.

## Solutions
List 3-5 distinct approaches with pros/cons for each.

## Trade-offs
Comparison table or summary of key trade-offs.

## Recommendation
The single best solution with rationale.`;

  console.log(`Brainstorming: "${topic}"...`);

  const result = await invokeClaudePhase(prompt, 'brainstorm', modelOverride, true);

  if (!result.success) {
    console.error(`Error: ${result.error ?? 'Unknown error'}`);
    process.exit(1);
  }

  const output = result.output ?? '';
  console.log(output);

  if (options.repo) {
    await createGitHubIssue(topic, output, options.repo, options.label);
  }
}

async function createGitHubIssue(
  topic: string,
  brainstormOutput: string,
  repo: string,
  labelsCsv?: string,
): Promise<void> {
  const [owner, repoName] = repo.split('/');
  if (!owner || !repoName) {
    console.error('Error: --repo must be in "owner/repo" format');
    process.exit(1);
  }

  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    console.error('Error: GITHUB_TOKEN environment variable required for issue creation');
    process.exit(1);
  }

  const octokit = new Octokit({ auth: token });
  const labels = labelsCsv ? labelsCsv.split(',').map((l) => l.trim()) : ['brainstorm'];

  const title = `Brainstorm: ${topic}`;
  const body = `*Generated by claude-swarm brainstorm*\n\n${brainstormOutput}`;

  const { data } = await octokit.issues.create({
    owner,
    repo: repoName,
    title,
    body,
    labels,
  });

  console.log(`\nCreated issue #${data.number}: ${data.html_url}`);
}

export const brainstormCommand = new Command('brainstorm')
  .description('Brainstorm solutions and optionally create GitHub issues')
  .argument('<topic>', 'Topic or question to brainstorm')
  .option('-c, --context <file>', 'Context file path for additional background')
  .option('-r, --repo <owner/repo>', 'Create GitHub issue from result')
  .option('-l, --label <labels>', 'Issue labels, comma-separated (default: brainstorm)')
  .option('-m, --model <model>', 'Model override (opus|sonnet|haiku)')
  .action(executeBrainstorm);
